server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybatis?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  指定Mapper文件路径
  mapper-locations: classpath:mapping/*Mapper.xml
#  指定PoJo对象路径，并起别名
  type-aliases-package: com.liujie.bean
#  配置mybatis的分页插件信息
#数据库
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params=count: countSql
#showSql
logging:
  level:
    com:
      example:
        mapper: debug